# Generated by Django 3.1.3 on 2020-11-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='level',
            field=models.IntegerField(verbose_name='Деңгей'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Есімі'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Баласы', to='history.pedigree', verbose_name='Әкесі'),
        ),
    ]
