# Generated by Django 3.1.3 on 2020-11-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20201118_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='history.pedigree', verbose_name='Әкесі'),
        ),
    ]
